### ISSUE TITLE
Failed to initialize JaCoCo

### ISSUE THREAD

**Issue by auermich93** [H2SO4T/COSMO#4]
Hi guys,

I tried to run COSMO in black box mode using a very simple BMI Calculator app (https://f-droid.org/packages/com.zola.bmi/). First, I decompiled the APK using apktool, inserted the debuggable attribute in the AndroidManifest.xml and re-packaged it (https://gist.github.com/nstarke/615ca3603fdded8aee47fab6f4917826). After that, I executed `python cli.py com.zola.bmi.apk`:

```
$ python cli.py com.zola.bmi.apk
29/09/2023 22:06:32> [INFO][apk_instrumenter][run_instrumentation()] Instrumenting apk file "com.zola.bmi.apk"
29/09/2023 22:06:32> [INFO][apk_instrumenter][instrument_apk()] Converting to Java bytecode with dex2jar command "C:\Users\Michael\Downloads\dex2jar-2.0\dex2jar-2.0\d2j-dex2jar.bat -f -e nul C:\Users\Michael\App
Data\Local\Temp\tmp9l34xgz2\com.zola.bmi.apk -o C:\Users\Michael\AppData\Local\Temp\tmp9l34xgz2\com.zola.bmi.jar"
29/09/2023 22:06:35> [INFO][apk_instrumenter][instrument_apk()] Instrumenting with Java command "C:\Users\Michael\.jdks\openjdk-15.0.2\bin\java.EXE -jar C:\Users\Michael\git\COSMO\lib\jacococli.jar instrument C:
\Users\Michael\AppData\Local\Temp\tmp9l34xgz2\com.zola.bmi.jar --dest C:\Users\Michael\AppData\Local\Temp\tmp9l34xgz2\jacoco"
29/09/2023 22:06:37> [INFO][apk_instrumenter][instrument_apk()] Converting Java to Dalvik with command "E:\Android\Android\Sdk\build-tools\31.0.0-rc3\dx.BAT -JXmx4g --dex --multi-dex --output=C:\Users\Michael\Ap
pData\Local\Temp\tmp9l34xgz2\dex C:\Users\Michael\AppData\Local\Temp\tmp9l34xgz2\jacoco C:\Users\Michael\git\COSMO\lib\jacocoagent.jar"
29/09/2023 22:06:43> [INFO][apk_instrumenter][instrument_apk()] Running sign command with default debug key "E:\Android\Android\Sdk\build-tools\31.0.0-rc3\apksigner.BAT sign --ks-pass pass:android --ks C:\Users\
Michael\git\COSMO\lib\debug.keystore C:\Users\Michael\AppData\Local\Temp\tmp9l34xgz2\com.zola.bmi.apk"
29/09/2023 22:06:44> [INFO][apk_instrumenter][instrument_apk()] Running align command "E:\Android\Android\Sdk\build-tools\31.0.0-rc3\zipalign.EXE -v -p -f 4 C:\Users\Michael\AppData\Local\Temp\tmp9l34xgz2\com.zo
la.bmi.apk.copy C:\Users\Michael\AppData\Local\Temp\tmp9l34xgz2\com.zola.bmi.apk"
29/09/2023 22:06:44> [INFO][apk_instrumenter][instrument_apk()] Files for apk "com.zola.bmi" saved in "C:\Users\Michael\git\COSMO\output_apks" directory
```
The instrumenation process looks fine. After that, I had to re-sign the instrumented APK since the installation failed and complained about a stripped signature:

```
$ adb install -g output_apks/com.zola.bmi.apk
Performing Streamed Install
adb: failed to install output_apks/com.zola.bmi.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl90500489.tmp/base.apk: META-INF/ANDROIDD.SF indicates /data/app/vmdl90500489.tmp/base.apk is signed using APK Signature Scheme v2, but no such signature was found. Signature stripped?]
```

I suppose you are using some outdated signing scheme, but I could fix that by using my own keystore and after re-signing the installation succeeded.  However, when I try to launch the app on the emulator the app crashes immediately with the following stack trace:

```
2023-09-29 22:08:38.854 3008-3008/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.zola.bmi, PID: 3008
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.zola.bmi/com.zola.bmi.BMIMain}: java.lang.RuntimeException: Failed to initialize JaCoCo.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2567)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.RuntimeException: Failed to initialize JaCoCo.
        at org.jacoco.agent.rt.internal_0000000.Offline.getRuntimeData(Offline.java:41)
        at org.jacoco.agent.rt.internal_0000000.Offline.getProbes(Offline.java:60)
        at com.zola.bmi.BMIMain.$jacocoInit(Unknown Source)
        at com.zola.bmi.BMIMain.<init>(Unknown Source)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1078)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2557)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
     Caused by: java.io.FileNotFoundException: / (Is a directory)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at org.jacoco.agent.rt.internal_0000000.output.FileOutput.openFile(FileOutput.java:68)
        at org.jacoco.agent.rt.internal_0000000.output.FileOutput.startup(FileOutput.java:50)
        at org.jacoco.agent.rt.internal_0000000.Agent.startup(Agent.java:129)
        at org.jacoco.agent.rt.internal_0000000.Agent.getInstance(Agent.java:54)
        at org.jacoco.agent.rt.internal_0000000.Offline.getRuntimeData(Offline.java:39)
        at org.jacoco.agent.rt.internal_0000000.Offline.getProbes(Offline.java:60) 
        at com.zola.bmi.BMIMain.$jacocoInit(Unknown Source) 
        at com.zola.bmi.BMIMain.<init>(Unknown Source) 
        at java.lang.Class.newInstance(Native Method) 
        at android.app.Instrumentation.newActivity(Instrumentation.java:1078) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2557) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

I am using a Nexus_5_API_25 emulator and the un-instrumented APK works as expected. Is this failure known to you? I will try to update to a more recent `dex2jar` version but since the instrumentation logs looked promising, I thought this was not necessary.
Or do I need to grant some additional permissions in the AndroidManifest.xml? 

Thanks in advance.

**Comment by auermich93** [comment]
I updated to the latest `dex2jar` version (2.3) but it didn't resolve the issue. Then, I tried to decompile the instrumented APK and noticed that some JaCoCo classes were added but not the `EndCoverageBroadcast` broadcast receiver class. I suppose you use the same mechanism for storing coverage in both modes? The broadcast receiver was consequently also not added to the AndroidManifest and unless you don't use a dynamic receiver this won't work.

**Comment by auermich93** [comment]
I finally got COSMO running by using a patched version discovered here https://github.com/ggiraldez/COSMO.

**Comment by auermich93** [comment]
The only remaining question is what's the command to build the coverage report in the black-box mode? Do I need to build a minimal gradle project including the jacoco-instrumenter-coverage.gradle file and locate the Java bytecode classes at the correct locations?

**Comment by auermich93** [comment]
The command to generate the coverage report is as follows:
`java -jar $COSMO_PATH/lib/jacococli.jar report $REPORT_PATH/coverage.ec --classfiles $INSTRUMENTED_JAR --html $REPORT_PATH`

Thanks to @ggiraldez.

**Comment by up201907932** [comment]
Hi, I keep getting this error.
[ERROR][apk_instrumenter][convert_to_dalvik()] Error during Java to Dalvik conversion command: 
PARSE ERROR:
unsupported class file version 52.0
...while parsing cosmo/receiver/EndCoverageBroadcast.class
1 error; aborting

I supose it has to do with the java version that I use to get the receiver.jar, when I run the ./gradlew install. If I use java 8 i get file version 52.0, if I use java 11 i get file version 55.0. Any ideias on what I should do @auermich93?
